### ISSUE TITLE
Save all treebank metadata to database

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-server#6]
We are still generating all the metadata every time. They are not changing so stop generating them every time.

**Comment by matyaskopp** [comment]
Metadata is changed when treebank or related tags are changed in administration. So if treebank or tag documentation:
https://github.com/ufal/perl-pmltq-server/blob/12adab011501759641a982693a5d8b9e166f642c/lib/PMLTQ/Server/Schema/Result/Treebank.pm#L171-L181
is changed cached metadata should be replaced


`schemas`, `node_types`, `relations` and `attributes` can be safely cached. This fields also the most time consuming ones.
https://github.com/ufal/perl-pmltq-server/blob/12adab011501759641a982693a5d8b9e166f642c/lib/PMLTQ/Server/Schema/Result/Treebank.pm#L160-L168

**Comment by matyaskopp** [comment]
75da4d9825ec1ff4586952b8f567cf089b638503
