### ISSUE TITLE
Change /:treebank/svg to GET to simplify caching

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-server#7]
Makes no sense to use this with POST

**Comment by matyaskopp** [comment]
https://github.com/ufal/perl-pmltq-server/commit/12adab011501759641a982693a5d8b9e166f642c
https://github.com/ufal/perl-pmltq-web/commit/d34d1ce2912c0a2ce419f5844f2ce7eac27e30c8

**Comment by matyaskopp** [comment]
fix next button in PMLTQ-WEB

**Comment by matyaskopp** [comment]
fixed with https://github.com/ufal/perl-pmltq-web/commit/c8d5090ffd711eb7af192d4d9de4abdf586e60d8
